### ISSUE TITLE
[EPIC] Move Controllers to Actions

### ISSUE THREAD

**Issue by Alroniks** [mspay/service-extras#5]
## Goal

The goal is to convert controllers, implemented by the MVC model, to Actions, according to ADR (Action-Domain-Responder) architecture. A list of available routes exists in old routes config, need to reimplement this list in a new application.

### Acceptance Criteria
- [ ] all old routes redefined and covered by new actions

### Tasklist
- [ ] Move HomeController to Verify and Home actions #6 
- [ ] Move RepositoryController to appropriate actions
- [ ] Move PackageController to appropriate actions

**Comment by alroniks** [comment]
Close this issue as epic was moved to milestone
